baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Ashwin Rajesh Achievements'


[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'light'

